package simplehttpserver.impl

sealed abstract class Status(val code: Int) {
  override def toString: String = getClass.getSimpleName
}

sealed abstract class Informational(override val code: Int) extends Status(code)
sealed abstract class Success(override val code: Int) extends Status(code)
sealed abstract class Redirection(override val code: Int) extends Status(code)
sealed abstract class ClientError(override val code: Int) extends Status(code)
sealed abstract class ServerError(override val code: Int) extends Status(code)

case object Continue extends Informational(100)
case object SwitchingProtocols extends Informational(101)
case object Processing extends Informational(102)

case object Ok extends Success(200)
case object Created extends Success(201)
case object Accepted extends Success(202)
case object Non_AuthoritativeInformation extends Success(203)
case object NoContent extends Success(204)
case object ResetContent extends Success(205)
case object PartialContent extends Success(206)
case object Multi_Status extends Success(207)
case object IMUsed extends Success(226)

case object MultipleChoices extends Redirection(300)
case object MovedPermanently extends Redirection(301)
case object Found extends Redirection(302)
case object SeeOther extends Redirection(303)
case object NotModified extends Redirection(304)
case object UseProxy extends Redirection(305)
case object TemporaryRedirect extends Redirection(307)
case object PermanentRedirect extends Redirection(308)

case object BadRequest extends ClientError(400)
case object Unauthorized extends ClientError(401)
case object PaymentRequired extends ClientError(402)
case object Forbidden extends ClientError(403)
case object NotFound extends ClientError(404)
case object MethodNotAllowed extends ClientError(405)
case object NotAcceptable extends ClientError(406)
case object ProxyAuthenticationRequired extends ClientError(407)
case object RequestTimeout extends ClientError(408)
case object Conflict extends ClientError(409)
case object Gone extends ClientError(410)
case object LengthRequired extends ClientError(411)
case object PreconditionFailed extends ClientError(412)
case object RequestEntityTooLarge extends ClientError(413)
case object Request_URITooLong extends ClientError(414)
case object UnsupportedMediaType extends ClientError(415)
case object RequeatedRangeNotSatisfiable extends ClientError(416)
case object ExpectationFailed extends ClientError(417)
case object ImATeapot extends ClientError(418)
case object UnprocessableEntity extends ClientError(422)
case object Locked extends ClientError(423)
case object FailedDependency extends ClientError(424)
case object UpgradeRequired extends ClientError(426)

case object InternalServerError extends ServerError(500)
case object NotImplemented extends ServerError(501)
case object BadGateway extends ServerError(502)
case object ServiceUnavailable extends ServerError(503)
case object GatewayTimeout extends ServerError(504)
case object HTTPVersionNotSupported extends ServerError(505)
case object VariantAlsoNegotiates extends ServerError(506)
case object InsufficientStorage extends ServerError(507)
case object BandwidthLimitExceeded extends ServerError(509)
case object NotExtended extends ServerError(510)
